### ISSUE TITLE
Allow importing just individual icons

### ISSUE THREAD

**Issue by archSeer** [egoist/vue-feather-icons#10]
Something like `import CheckIcon from 'vue-feather-icons/CheckIcon';` would shrink down the build size significantly via webpack if I'm only using a few of the icons from the set (there's a few hundred icons, but I'm only using about 10-20 max).

I tried doing `import CheckIcon from 'vue-feather-icons/components/CheckIcon' based on https://github.com/egoist/vue-feather-icons/blob/master/build.js#L34, but the built npm package only has

**Comment by egoist** [comment]
`import { CheckIcon } from 'vue-feather-icons'` will also only import what you need

**Comment by archSeer** [comment]
Yes, but this way the entire `.es.js` file then gets included at build time:

```
-rw-r--r--  1 speed  staff   213K Apr  2 12:19 vue-feather-icons.es.js
```

<img width="455" alt="screen shot 2018-05-15 at 00 35 43" src="https://user-images.githubusercontent.com/1372918/40007500-7f92dfb8-578c-11e8-80b9-d870e672b8d7.png">

It's similar to lodash, `import { ... } from 'lodash';` will import the entire library, whereas `import from 'lodash/...'` will only import whichever modules needed at build time, reducing the final file size.

**Comment by egoist** [comment]
@archSeer unused imports will be striped away when minified with uglifyjs, it's a bit different for lodash tree-shaking to work too: https://github.com/webpack/webpack/issues/1750#issuecomment-388638028

**Comment by egoist** [comment]
but I agree that per-file icons would help if you don't wanto use a minifier

**Comment by egoist** [comment]
Added in v4.7.1 https://github.com/egoist/vue-feather-icons#tree-shaking
