### ISSUE TITLE
SmileIcon is not available

### ISSUE THREAD

**Issue by jsinhSolanki** [egoist/vue-feather-icons#15]
Hey, I want to use smile icon but it is not displaying.

In your icons page [https://vue-feather-icons.netlify.com/](https://vue-feather-icons.netlify.com/), There is smile icon but it's not displaying.

**Comment by egoist** [comment]
what do you mean by not displaying?

**Comment by jsinhSolanki** [comment]
If I use `SmileIcon` its not rendering.

This is what outputtted in dev tool.
I first coded `ThumbsUpIcon` icon and then `SmileIcon`. `ThumbsUp` icon is showing in page. and correctly displays in dev tool's html but there's something with `SmileIcon`.
![html](https://user-images.githubusercontent.com/31243533/51744229-243af300-20c5-11e9-9ccb-07c272bc8ed1.PNG)
As you can see when I use `SmileIcon` i get commented lines
later I checked in node_modules' file `vue-feather-icons.js` but there's no icon like `SmileIcon`.

Now in my web page.
![page](https://user-images.githubusercontent.com/31243533/51744251-34eb6900-20c5-11e9-9e71-937d4f6baff5.PNG)

**Comment by egoist** [comment]
well I'm sure it's not a bug in this lib, you can check out the entire code of this icon: https://unpkg.com/vue-feather-icons@4.10.0/icons/SmileIcon.js

**Comment by egoist** [comment]
<img width="441" alt="屏幕快照 2019-06-10 下午10 33 22" src="https://user-images.githubusercontent.com/8784712/59202779-ccaea700-8bcf-11e9-808e-08dfad4b8974.png">

**Comment by egoist** [comment]
<img width="441" alt="屏幕快照 2019-06-10 下午10 33 22" src="https://user-images.githubusercontent.com/8784712/59202779-ccaea700-8bcf-11e9-808e-08dfad4b8974.png">
