### ISSUE TITLE
Bump to feather-icons 4.21.0 (also proposal for version-sync)

### ISSUE THREAD

**Issue by andreasvirkus** [egoist/vue-feather-icons#16]
Identical to my request for the [4.8.0](https://github.com/egoist/vue-feather-icons/pull/13) update, but since I don't have yarn installed atm, was wondering if you'd be willing to bump the version yourself (as I won't be able to provide a new yarn lock-file)

Would there also be a possibility to somehow make this sync automatic? E.g. when a new tag is pushed to feather-icons, we'd bump the dependency version in this package as well?

**Comment by egoist** [comment]
Done, just added dependabot: https://github.com/egoist/vue-feather-icons/pull/30
