### ISSUE TITLE
Name mapping

### ISSUE THREAD

**Issue by christianmalek** [egoist/vue-feather-icons#2]
The names of the functional components use a different naming convention than the feather icons. I think it would be helpful to explain with a little example how you adapted the componet names.

Example:

official: `edit-2`
component name: `Edit2`

**Comment by egoist** [comment]
Ah yeah, maybe make a website to list these components.

**Comment by christianmalek** [comment]
See https://vue-feather-icons.netlify.com/

**Comment by egoist** [comment]
we export `Edit2Icon` by default but somehow you can use both `edit-2-icon` and `edit2-icon` in template like:

```vue
<template>
  <div>
    <edit2-icon></edit2-icon>
    <edit-2-icon></edit-2-icon>
  </div>
</template>

<script>
import { Edit2Icon } from 'vue-feather-icons'

export default {
  components: {
    Edit2Icon
  }
}
</script>
```

**Comment by christianmalek** [comment]
Good to know. :)
