### ISSUE TITLE
[REQUEST] Discord & WhatsApp icon.

### ISSUE THREAD

**Issue by Julianvschijndel** [egoist/vue-feather-icons#49]
Hi,

I love this package, but where is there no icon for WhatsApp and Discord?
I would really like it to have those. Will these ever be added?

Hope to hear soon.

**Comment by Julianvschijndel** [comment]
Closed this myself due no support. Will use another icon package then.

**Comment by andreasvirkus** [comment]
@TheDevJulian you should file all icon requests to the original Feather icon project here - https://github.com/feathericons/feather. This is just a vue wrapper project for those icons
