### ISSUE TITLE
vue-feather-icons.egoist.sh is not available.

### ISSUE THREAD

**Issue by zhuowenli** [egoist/vue-feather-icons#51]
![image](https://user-images.githubusercontent.com/9620783/87373453-4a579a00-c5bc-11ea-9866-2f2c2ae27726.png)

**Comment by egoist** [comment]
hmm it works for me.

**Comment by zhuowenli** [comment]
I add `8.8.8.8` to DNS, and it work now... It was `114.114.114.114` before.
