### ISSUE TITLE
Icon size?

### ISSUE THREAD

**Issue by andrewmillen** [egoist/vue-feather-icons#6]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/egoist/vue-feather-icons/issues/6)

How can I change the icon size? Font-size doesn't work, presumably because they're being converted to svgs. Changing the SVG width/height doesn't work either (because it's not changing the viewbox).

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#37 feat: icon sizing](https://issuehunt.io/r/egoist/vue-feather-icons/pull/37)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/vue-feather-icons/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by egoist** [comment]
Change the width and height with CSS should work.

btw I think we can add a prop to control this.

**Comment by calebporzio** [comment]
@andrewmillen - here is my helper class to make the SVG adjust to the font size of it's container:

```
.svg-icon {
    height: 1em;
    margin-top: -4px;
    pointer-events: none;
    vertical-align: middle;
    width: 1em;
}
```

So now the icon in here `<h1>Hello World <ClockIcon class="svg-icon"/></h1>` will be the same height as the text.

Hope this helps!

Also, it would be awesome if there was some way to add this by default so I don't have to add a class every time.

**Comment by SiamKreative** [comment]
Agreed with @calebporzio, I think this should be the default :)

**Comment by atymic** [comment]
I've opened a PR in #37, let me know what you think.
