### ISSUE TITLE
Import all of them?

### ISSUE THREAD

**Issue by ConsoleTVs** [egoist/vue-feather-icons#7]
Is there a way to import all of them at once?

**Comment by egoist** [comment]
`import * as icons from 'vue-feather-icons`

**Comment by ConsoleTVs** [comment]
Is there a need to register the components?

**Comment by egoist** [comment]
Sure, if you're using template.

**Comment by uu109** [comment]
Excuse me, I wrote down `import * as icons from 'vue-feather-icons'` in main.js. 
After that, what else do I need to do to use any icon in different .vue documents?
